import Navbar from "@/components/Navbar";
import "./globals.css";
import Footer from "@/components/Footer";
import ContactButtons from "@/components/ContactButton";
import { DemoModalProvider } from "@/components/DemoModalProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-dvh overflow-x-hidden bg-white text-slate-900 antialiased">
        <DemoModalProvider>
          <Navbar />
          {children}
          <Footer />
          <ContactButtons />
        </DemoModalProvider>
      </body>
    </html>
  );
}
